# Generated by Django 3.1.7 on 2021-03-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_services_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services_users',
            name='user',
        ),
    ]
