# Generated by Django 3.1.7 on 2021-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_services_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_users',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='services_users',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
