# Generated by Django 3.1.7 on 2021-03-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210318_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_users',
            name='price2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='services_users',
            name='price3',
            field=models.IntegerField(null=True),
        ),
    ]
