# Generated by Django 3.1.7 on 2021-03-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_description',
            name='avaible',
            field=models.BooleanField(default=True),
        ),
    ]
